/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixShopifyProductCsvRouteImport } from './routes/fix-shopify-product-csv'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ShopifyCsvImportErrorsRouteImport } from './routes/shopify-csv-import-errors'
import { Route as ShopifyCsvImportNotWorkingRouteImport } from './routes/shopify-csv-import-not-working'
import { Route as ShopifyCsvRequiredColumnsRouteImport } from './routes/shopify-csv-required-columns'
import { Route as ShopifyInventoryPolicyCsvErrorRouteImport } from './routes/shopify-inventory-policy-csv-error'
import { Route as ShopifyCsvValidatorRouteImport } from './routes/shopify-csv-validator'
import { Route as SupplierCsvToShopifyRouteImport } from './routes/supplier-csv-to-shopify'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixShopifyProductCsvRoute = FixShopifyProductCsvRouteImport.update({
  id: '/fix-shopify-product-csv',
  path: '/fix-shopify-product-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyCsvImportErrorsRoute = ShopifyCsvImportErrorsRouteImport.update({
  id: '/shopify-csv-import-errors',
  path: '/shopify-csv-import-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyCsvImportNotWorkingRoute = ShopifyCsvImportNotWorkingRouteImport.update({
  id: '/shopify-csv-import-not-working',
  path: '/shopify-csv-import-not-working',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyCsvRequiredColumnsRoute = ShopifyCsvRequiredColumnsRouteImport.update({
  id: '/shopify-csv-required-columns',
  path: '/shopify-csv-required-columns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyInventoryPolicyCsvErrorRoute =
  ShopifyInventoryPolicyCsvErrorRouteImport.update({
    id: '/shopify-inventory-policy-csv-error',
    path: '/shopify-inventory-policy-csv-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopifyCsvValidatorRoute = ShopifyCsvValidatorRouteImport.update({
  id: '/shopify-csv-validator',
  path: '/shopify-csv-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierCsvToShopifyRoute = SupplierCsvToShopifyRouteImport.update({
  id: '/supplier-csv-to-shopify',
  path: '/supplier-csv-to-shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fix-shopify-product-csv': typeof FixShopifyProductCsvRoute
  '/mcp': typeof McpRoute
  '/shopify-csv-import-errors': typeof ShopifyCsvImportErrorsRoute
  '/shopify-csv-import-not-working': typeof ShopifyCsvImportNotWorkingRoute
  '/shopify-csv-required-columns': typeof ShopifyCsvRequiredColumnsRoute
  '/shopify-inventory-policy-csv-error': typeof ShopifyInventoryPolicyCsvErrorRoute
  '/shopify-csv-validator': typeof ShopifyCsvValidatorRoute
  '/supplier-csv-to-shopify': typeof SupplierCsvToShopifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fix-shopify-product-csv': typeof FixShopifyProductCsvRoute
  '/mcp': typeof McpRoute
  '/shopify-csv-import-errors': typeof ShopifyCsvImportErrorsRoute
  '/shopify-csv-import-not-working': typeof ShopifyCsvImportNotWorkingRoute
  '/shopify-csv-required-columns': typeof ShopifyCsvRequiredColumnsRoute
  '/shopify-inventory-policy-csv-error': typeof ShopifyInventoryPolicyCsvErrorRoute
  '/shopify-csv-validator': typeof ShopifyCsvValidatorRoute
  '/supplier-csv-to-shopify': typeof SupplierCsvToShopifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fix-shopify-product-csv': typeof FixShopifyProductCsvRoute
  '/mcp': typeof McpRoute
  '/shopify-csv-import-errors': typeof ShopifyCsvImportErrorsRoute
  '/shopify-csv-import-not-working': typeof ShopifyCsvImportNotWorkingRoute
  '/shopify-csv-required-columns': typeof ShopifyCsvRequiredColumnsRoute
  '/shopify-inventory-policy-csv-error': typeof ShopifyInventoryPolicyCsvErrorRoute
  '/shopify-csv-validator': typeof ShopifyCsvValidatorRoute
  '/supplier-csv-to-shopify': typeof SupplierCsvToShopifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fix-shopify-product-csv'
    | '/mcp'
    | '/shopify-csv-import-errors'
    | '/shopify-csv-import-not-working'
    | '/shopify-csv-required-columns'
    | '/shopify-inventory-policy-csv-error'
    | '/shopify-csv-validator'
    | '/supplier-csv-to-shopify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fix-shopify-product-csv'
    | '/mcp'
    | '/shopify-csv-import-errors'
    | '/shopify-csv-import-not-working'
    | '/shopify-csv-required-columns'
    | '/shopify-inventory-policy-csv-error'
    | '/shopify-csv-validator'
    | '/supplier-csv-to-shopify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/fix-shopify-product-csv'
    | '/mcp'
    | '/shopify-csv-import-errors'
    | '/shopify-csv-import-not-working'
    | '/shopify-csv-required-columns'
    | '/shopify-inventory-policy-csv-error'
    | '/shopify-csv-validator'
    | '/supplier-csv-to-shopify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixShopifyProductCsvRoute: typeof FixShopifyProductCsvRoute
  McpRoute: typeof McpRoute
  ShopifyCsvImportErrorsRoute: typeof ShopifyCsvImportErrorsRoute
  ShopifyCsvImportNotWorkingRoute: typeof ShopifyCsvImportNotWorkingRoute
  ShopifyCsvRequiredColumnsRoute: typeof ShopifyCsvRequiredColumnsRoute
  ShopifyInventoryPolicyCsvErrorRoute: typeof ShopifyInventoryPolicyCsvErrorRoute
  ShopifyCsvValidatorRoute: typeof ShopifyCsvValidatorRoute
  SupplierCsvToShopifyRoute: typeof SupplierCsvToShopifyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-shopify-product-csv': {
      id: '/fix-shopify-product-csv'
      path: '/fix-shopify-product-csv'
      fullPath: '/fix-shopify-product-csv'
      preLoaderRoute: typeof FixShopifyProductCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-csv-import-errors': {
      id: '/shopify-csv-import-errors'
      path: '/shopify-csv-import-errors'
      fullPath: '/shopify-csv-import-errors'
      preLoaderRoute: typeof ShopifyCsvImportErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-csv-import-not-working': {
      id: '/shopify-csv-import-not-working'
      path: '/shopify-csv-import-not-working'
      fullPath: '/shopify-csv-import-not-working'
      preLoaderRoute: typeof ShopifyCsvImportNotWorkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-csv-required-columns': {
      id: '/shopify-csv-required-columns'
      path: '/shopify-csv-required-columns'
      fullPath: '/shopify-csv-required-columns'
      preLoaderRoute: typeof ShopifyCsvRequiredColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-inventory-policy-csv-error': {
      id: '/shopify-inventory-policy-csv-error'
      path: '/shopify-inventory-policy-csv-error'
      fullPath: '/shopify-inventory-policy-csv-error'
      preLoaderRoute: typeof ShopifyInventoryPolicyCsvErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-csv-validator': {
      id: '/shopify-csv-validator'
      path: '/shopify-csv-validator'
      fullPath: '/shopify-csv-validator'
      preLoaderRoute: typeof ShopifyCsvValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-csv-to-shopify': {
      id: '/supplier-csv-to-shopify'
      path: '/supplier-csv-to-shopify'
      fullPath: '/supplier-csv-to-shopify'
      preLoaderRoute: typeof SupplierCsvToShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixShopifyProductCsvRoute: FixShopifyProductCsvRoute,
  McpRoute: McpRoute,
  ShopifyCsvImportErrorsRoute: ShopifyCsvImportErrorsRoute,
  ShopifyCsvImportNotWorkingRoute: ShopifyCsvImportNotWorkingRoute,
  ShopifyCsvRequiredColumnsRoute: ShopifyCsvRequiredColumnsRoute,
  ShopifyInventoryPolicyCsvErrorRoute: ShopifyInventoryPolicyCsvErrorRoute,
  ShopifyCsvValidatorRoute: ShopifyCsvValidatorRoute,
  SupplierCsvToShopifyRoute: SupplierCsvToShopifyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
